# use Docker-based container (instead of OpenVZ)
sudo: false

language: scala
scala:
   - 2.11.2
jdk:
  - oraclejdk8
  - openjdk8

notifications:
  email:
    - garygaowork@gmail.com

# https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/8
dist: trusty



# script: sbt ++$TRAVIS_SCALA_VERSION check-gen-type-classes test
